version: '2'
services:
  factorio:
    build: .
    ports:
      - "34197:34197/udp"
    volumes:
      - /factorio/server:/factorio
  factorio-notifications:
    depends_on: 
      - factorio
    image: "ttobias/logfile-notifications"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /factorio/notifications/config.yaml:/config.yaml
      - /factorio/server/log/:/log
