#!/bin/sh
DIR=/opt/factorio/docker-container/0.16

cd ${DIR}
RCONPW=$(cat /opt/factorio/data/config/rconpw)

echo "- Checking for active players..."
/opt/factorio/rcon-client/src/rcon -1 -H localhost -p 27015 -P ${RCONPW} /players | grep -i online
if [ $? -eq 0 ]; then
    echo "  Found active players. Exit"
    exit
else
    echo "  No active players"
fi

echo
/opt/factorio/docker-container/updater/updater -dockerfile "$DIR/Dockerfile" -composefile "$DIR/docker-compose.yml"
if [ $? -eq 0 ]; then
    docker-compose -f $DIR/docker-compose.yml down
    docker-compose -f $DIR/docker-compose.yml build
    docker-compose -f $DIR/docker-compose.yml up -d
fi

