version: '2'
services:
  factorio:
    build: .
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - ../../data:/factorio
  factorio-notifications:
    depends_on: 
      - factorio
    image: "ttobias/logfile-notifications"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ../../notifications/config.yaml:/config.yaml
      - ../../data/log/:/log
